#meant to be deployed with something like pdq, intune, etc

$registryPath = "HKLM:\SOFTWARE\JavaTracking"


if (-not (Test-Path $registryPath)) {
    Write-Output "Registry path does not exist. Exiting script."
    exit
}


$uninstallRegistryKeys = @(
    "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall",
    "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
)

# loops through registries to see anywhere where java may be installed 
foreach ($key in $uninstallRegistryKeys) {
    $subKeys = Get-ChildItem -Path $key -ErrorAction SilentlyContinue
    foreach ($subKey in $subKeys) {
        $displayName = (Get-ItemProperty -Path $subKey.PSPath -Name "DisplayName" -ErrorAction SilentlyContinue).DisplayName
        $uninstallString = (Get-ItemProperty -Path $subKey.PSPath -Name "UninstallString" -ErrorAction SilentlyContinue).UninstallString

        if ($displayName -and $displayName -like "Java*") {
            Write-Output "Found Java installation: $displayName"

            if ($uninstallString) {
                Write-Output "Preparing to uninstall $displayName..."

                # executes the uninstall string
                if ($uninstallString -match "msiexec") {
                    $productCode = $uninstallString -replace ".*msiexec.*\s*\/x\s*", "" -replace "\s.*", ""
                    Start-Process -FilePath "msiexec.exe" -ArgumentList "/x $productCode /quiet" -Wait -NoNewWindow
                } else {
                    Start-Process -FilePath $uninstallString -Wait -NoNewWindow
                }

                # tells us if uninstall succesful. 
                if ($LASTEXITCODE -eq 0) {
                    Write-Output "Successfully uninstalled $displayName."

                    # remove prefetch files that are generated by java usage on the machine to avoid future scanning conflicts
                    $prefetchFiles = Get-ChildItem -Path "C:\Windows\Prefetch\" -Filter "JAVA*.pf" -ErrorAction SilentlyContinue
                    foreach ($file in $prefetchFiles) {
                        Remove-Item -Path $file.FullName -Force -ErrorAction SilentlyContinue
                        Write-Output "Removed Prefetch file: $($file.FullName)"
                    }

                    # creates our registry key that tells us java was uninstalled 
                    $javaRemovedDate = Get-Date
                    Set-ItemProperty -Path $registryPath -Name "JavaRemovedDate" -Value $javaRemovedDate.ToString()
                    Write-Output "Registry updated with 'JavaRemovedDate': $javaRemovedDate"

                } else {
                    Write-Output "Failed to uninstall $displayName. Please check manually."
                }
            } else {
                Write-Output "No uninstall string found for $displayName."
            }
        }
    }
}

Write-Output "Uninstallation process complete. Please verify in Control Panel or manually remove any remaining Java components if needed."
